# Generated by Django 4.2.3 on 2023-08-08 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_examdivision_examroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+$', 'ID contains non-digit characters.')]),
        ),
        migrations.AlterField(
            model_name='examdivision',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+$', 'ID contains non-digit characters.')]),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+$', 'ID contains non-digit characters.')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+$', 'ID contains non-digit characters.')]),
        ),
    ]
