# Generated by Django 4.2.3 on 2023-08-08 08:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_department_id_alter_examdivision_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+$', 'ID contains non-digit characters.')])),
                ('name', models.TextField()),
                ('accepted_departments', models.ManyToManyField(related_name='accepted_examinees', to='db.department')),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.examroom')),
                ('final_accepted_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_accepted_examinees', to='db.department')),
            ],
        ),
    ]
